/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CurrentTime {
        "includeDate": boolean;
        "reloadInterval": number;
    }
    interface RelativeTime {
        "date": Date;
        "reloadInterval": number;
    }
}
declare global {
    interface HTMLCurrentTimeElement extends Components.CurrentTime, HTMLStencilElement {
    }
    var HTMLCurrentTimeElement: {
        prototype: HTMLCurrentTimeElement;
        new (): HTMLCurrentTimeElement;
    };
    interface HTMLRelativeTimeElement extends Components.RelativeTime, HTMLStencilElement {
    }
    var HTMLRelativeTimeElement: {
        prototype: HTMLRelativeTimeElement;
        new (): HTMLRelativeTimeElement;
    };
    interface HTMLElementTagNameMap {
        "current-time": HTMLCurrentTimeElement;
        "relative-time": HTMLRelativeTimeElement;
    }
}
declare namespace LocalJSX {
    interface CurrentTime {
        "includeDate"?: boolean;
        "reloadInterval"?: number;
    }
    interface RelativeTime {
        "date"?: Date;
        "reloadInterval"?: number;
    }
    interface IntrinsicElements {
        "current-time": CurrentTime;
        "relative-time": RelativeTime;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "current-time": LocalJSX.CurrentTime & JSXBase.HTMLAttributes<HTMLCurrentTimeElement>;
            "relative-time": LocalJSX.RelativeTime & JSXBase.HTMLAttributes<HTMLRelativeTimeElement>;
        }
    }
}
